test_distance_failures (unittest.loader._FailedTest.test_distance_failures) ... ERROR

======================================================================
ERROR: test_distance_failures (unittest.loader._FailedTest.test_distance_failures)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_distance_failures
Traceback (most recent call last):
  File "C:\Users\yo\AppData\Local\Programs\Python\Python313\Lib\unittest\loader.py", line 137, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'tests.test_distance_failures'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
